// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scjzawibacootyibfvgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjanphd2liYWNvb3R5aWJmdmdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTI1MjEsImV4cCI6MjA3MDMyODUyMX0.zsns3TnrEJKBfPH9GSFW8XFojHbD-mI8Zfwwn-YKqAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});