// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krfohcexjacmraosjwic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyZm9oY2V4amFjbXJhb3Nqd2ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjM1MjMsImV4cCI6MjA2OTAzOTUyM30.v2hOE52hW8tfnExpYXz1v_akpIP_EoEHcdowGyd0AKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});